//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Entities.Concrete
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmuaNfcContext : DbContext
    {
        public EmuaNfcContext()
            : base("name=EmuaNfcContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NfcCompany> NfcCompany { get; set; }
        public virtual DbSet<NfcCompanyDeskAlarm> NfcCompanyDeskAlarm { get; set; }
        public virtual DbSet<NfcDesk> NfcDesk { get; set; }
        public virtual DbSet<NfcDeskCategory> NfcDeskCategory { get; set; }
        public virtual DbSet<NfcMenu> NfcMenu { get; set; }
        public virtual DbSet<NfcTag> NfcTag { get; set; }
    }
}
