//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Entities.Concrete
{
	using Project.Core.Entities;
	using System;
	using System.Collections.Generic;

	public partial class NfcDeskCategory:IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NfcDeskCategory()
        {
            this.NfcDesk = new HashSet<NfcDesk>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CompanyId { get; set; }
    
        public virtual NfcCompany NfcCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NfcDesk> NfcDesk { get; set; }
    }
}
